[build]
  command = "npm run build"
  publish = "build"
  
  # Environment variables should be under [build.environment]
  [build.environment]
    NODE_VERSION = "20.18.0"
    CI = "false"

[functions]
  directory = "netlify/functions"
